# Product Review with Multi Nomial Naive Bayes

# Women Cloth Reviews Prediction

# The Multinomial Naive Bayes Classifier is suitable for classification with discrete feature(e.g; word counts for text classification).The Multinomial distribution normally require integer feature counts. however in practice ,fractional counts such as tf-idf may also work.

Import Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Import Dataset

In [2]:
df=pd.read_csv('Women.csv')

In [3]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [5]:
df.shape

(23486, 11)

#Missing Values

In [6]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [7]:
df[df['Review Text']==""]=np.NaN

In [8]:
df['Review Text'].fillna("No Review",inplace=True)

In [9]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [10]:
#Recategorise Rating as Poor(0) and Good(1) 

In [11]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [12]:
#re-rating 1,2,3 as 0 and 4,5 as 1
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [13]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

# Define Target(y) and Feature(x)

In [14]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [15]:
x=df['Review Text']
y=df['Rating']

In [16]:
df['Rating'].value_counts()

1.0    18208
0.0     5278
Name: Rating, dtype: int64

# Train_Test_Split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

In [19]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((18788,), (4698,), (18788,), (4698,))

    # Get Feature text conversion to token

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
cv=CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2,3), stop_words='english', max_features=5000)

In [22]:
x_train=cv.fit_transform(x_train)

In [23]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 bought', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [24]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
x_test=cv.fit_transform(x_test)

In [26]:
cv.get_feature_names_out()

array(['00 regular', '10 12', '10 12 tops', ..., 'zipper doesn',
       'zipper little', 'zipper tried'], dtype=object)

In [27]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

#Get Model Train

In [28]:
from sklearn.naive_bayes import MultinomialNB

In [29]:
model=MultinomialNB()

In [30]:
model.fit(x_train,y_train)

MultinomialNB()

#Model Prediction

In [31]:
y_pred=model.predict(x_test)

In [32]:
y_pred.shape

(4698,)

In [33]:
y_pred

array([1., 1., 1., ..., 1., 1., 0.])

#Get Probability of Each Predicted Class

In [34]:
model.predict_proba(x_test)

array([[0.17165891, 0.82834109],
       [0.14959805, 0.85040195],
       [0.22242921, 0.77757079],
       ...,
       [0.03837531, 0.96162469],
       [0.22242921, 0.77757079],
       [0.69398101, 0.30601899]])

#Model Evalution

In [35]:
from sklearn.metrics import confusion_matrix,classification_report

In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.30      0.25      0.27      1099
         1.0       0.78      0.82      0.80      3599

    accuracy                           0.69      4698
   macro avg       0.54      0.53      0.54      4698
weighted avg       0.67      0.69      0.68      4698



In [37]:
confusion_matrix(y_test,y_pred)

array([[ 270,  829],
       [ 639, 2960]], dtype=int64)